plt.figure()
plt.plot(mse)
plt.grid()
plt.title('MSE')
plt.xlabel('Iteration')
plt.ylabel('MSE')
plt.savefig('MSE.png')
plt.show()

plt.figure()
plt.plot(classification_error_history)
plt.grid()
plt.title('Classification Error')
plt.xlabel('Iteration')
plt.ylabel('Classification Error')
plt.savefig('classification_error.png')
plt.show()

weights1_history_np = np.array(weights1_history)
plt.figure()
for input_node in range(weights1_history_np.shape[2]):
    for hidden_node in range(weights1_history_np.shape[1]):
        plt.plot(weights1_history_np[:, hidden_node, input_node], label=f'Weight {hidden_node + 1},{input_node + 1}')
plt.title('Weights History (Input Layer)')
plt.grid()
plt.xlabel('Iteration')
plt.ylabel('Weight Value')
plt.legend()
plt.savefig('weights_input.png')
plt.show()

weights2_history_np = np.array(weights2_history)
plt.figure()
for i in range(weights2_history_np.shape[1]):
    plt.plot(weights2_history_np[:, i], label=f'Weight {i + 1}')
plt.grid()
plt.title('Weights History (Hidden Layer)')
plt.xlabel('Iteration')
plt.ylabel('Weight Value')
plt.legend()
plt.savefig('weights_hidden.png')
plt.show()